[workspace]
members = [
    "drand",
]
resolver = "2"

[workspace.package]
edition = "2021"
authors = ["Ideal Labs <hello@idealabs.network>"]
repository = "https://github.com/ideal-lab5/pallets"
homepage = "https://idealabs.network"